name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    env:
        SLURM: "latest"
    strategy:
      matrix:
        version:
          - '1.4'
          - '1.7'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x86
          - x64
        exclude:
          # Remove some configurations from the build matrix to reduce CI time.
          # See https://github.com/marketplace/actions/setup-julia-environment
          # MacOS not available on x86
          - {os: 'macOS-latest', arch: 'x86'}
          # Don't test on all versions
          - {os: 'macOS-latest', version: '1.1'}
          - {os: 'macOS-latest', version: '1.2'}
          - {os: 'macOS-latest', version: '1.3'}

    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Start Slurm Docker image
        run: |
          docker pull giovtorres/docker-centos7-slurm:$SLURM
          docker run -d -it -h ernie -v $(pwd):/SlurmTools -v $(julia -e 'print(dirname(Sys.BINDIR))'):/julia --name slurm-$SLURM giovtorres/docker-centos7-slurm:$SLURM
	  - name: Instantiate package
	    run: docker exec slurm-$SLURM /julia/bin/julia --project=/SlurmTools -e 'using Pkg; Pkg.instantiate(verbose=true); Pkg.build(verbose=true)'
      - name: Run Tests
        run: docker exec slurm-$SLURM /julia/bin/julia --project=/SlurmTools -e 'using Pkg; Pkg.test()'
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.7'
      - uses: julia-actions/julia-buildpkg@latest
      # - run: julia --project=docs -e '
      #     using Pkg;
      #     Pkg.develop(PackageSpec(; path=pwd()));
      #     Pkg.instantiate();'
      # - run: julia --project=docs docs/make.jl
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # Needed due to https://github.com/JuliaDocs/Documenter.jl/issues/1177
      #     DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
